process.on("uncaughtException", (error: Error) => {
	console.error("Excepci√≥n no capturada:", error);
});
